debug: true
spring:
  application:
    name: api
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:db/migrations

api:
  secrets:
    public: file:${PUBLIC_KEY}
    private: file:${PRIVATE_KEY}
  dev: true

aws:
  region: ${AWS_REGION:us-east-1}
  bucket: ${AWS_BUCKET}
  access: ${AWS_ACCESS}
  secret: ${AWS_SECRET}
