services:
  postgres:
    container_name: unilib_postgres
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    networks:
      - unilib-network

networks:
  unilib-network:
    driver: bridge