CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE book (
    id UUID PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    available BOOLEAN NOT NULL,
    description TEXT,
    image VARCHAR(255),
    pdf VARCHAR(255),
    has_ebook BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);