name: Spring Boot CI/CD to EC2

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_REPO }}

  deploy:
    environment: production
    runs-on: self-hosted
    needs: build
    steps:
      - name: Deploy to EC2
        run: |
          docker pull ${{ vars.DOCKERHUB_REPO }}:latest
          docker stop spring-boot-app || true
          docker rm spring-boot-app || true
          
          docker run -d \
          --name spring-boot-app \
          -p 8080:8080 \
          
          -e DB_USER=${{ secrets.DB_USER }} \
          -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
          -e DB_URL=${{ secrets.DB_URL }} \
          
          -e DEV_MODE=${{ vars.DEV_MODE }} \
          
          -e AWS_ACCESS=${{ secrets.AWS_ACCESS }} \
          -e AWS_SECRET=${{ secrets.AWS_SECRET }} \
          -e AWS_BUCKET=${{ secrets.AWS_BUCKET }} \
          -e AWS_REGION=${{ secrets.AWS_REGION }} \
          
          -e PUBLIC_KEY_CONTENT="${{ secrets.PUBLIC_KEY }}" \
          -e PRIVATE_KEY_CONTENT="${{ secrets.PRIVATE_KEY }}" \
          -e PUBLIC_KEY=/app/keys/public.pem \
          -e PRIVATE_KEY=/app/keys/private.pem \
          ${{ vars.DOCKERHUB_REPO }}:latest