name: Spring Boot CI/CD to EC2

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_REPO }}

  deploy:
    environment: production
    runs-on: self-hosted
    needs: build
    steps:
      - name: Create env file
        run: |
          cat <<EOF > ./env.list
          DOMAIN=${{ vars.DOMAIN }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_URL=${{ secrets.DB_URL }}
          DEV_MODE=${{ vars.DEV_MODE }}
          AWS_ACCESS=${{ secrets.AWS_ACCESS }}
          AWS_SECRET=${{ secrets.AWS_SECRET }}
          AWS_BUCKET=${{ secrets.AWS_BUCKET }}
          AWS_REGION=${{ secrets.AWS_REGION }}
          PUBLIC_KEY_CONTENT="${{ secrets.PUBLIC_KEY_CONTENT }}"
          PRIVATE_KEY_CONTENT="${{ secrets.PRIVATE_KEY_CONTENT }}"
          DOCKERHUB_REPO=${{ vars.DOCKERHUB_REPO }}
          EOF

      - name: Deploy to EC2
        run: |
          sudo docker compose --env-file ./env.list up -d
